# Generated by Django 4.2.1 on 2023-06-05 15:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Имя пользователя')),
                ('uuid_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен uuid')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('audio', models.FileField(upload_to='', verbose_name='Аудиозапись')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID-идентификатор аудио')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['audio'],
            },
        ),
    ]
