# Generated by Django 4.2.1 on 2023-05-22 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_uuid_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Аудиозапись')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID-идентификатор аудио')),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uuid_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен uuid'),
        ),
    ]
